sonar.projectKey=p92-checklist
sonar.projectName=p92-checklist
sonar.sources=lib,test
sonar.exclusions=build/**,android/**,ios/**,assets/**,assets_raw/**,play-assets/**,docs/**,test/screenshots/**,test/frames/**
sonar.coverage.exclusions=lib/main.dart
sonar.dart.file.suffixes=.dart
sonar.javascript.file.suffixes=
sonar.dart.analyzer.mode=MANUAL
sonar.dart.analyzer.report.mode=MACHINE
sonar.dart.analyzer.report.path=.dart_analysis.txt
sonar.flutter.coverage.reportPath=coverage/lcov.info
sonar.flutter.tests.reportPath=coverage/test-report.json
